### ISSUE TITLE
Add capability to hide keyboard

### ISSUE THREAD

**Issue by amuthansakthivel** [selenide/selenide-appium#101]
## The problem : Feature request
Add capability to hide keyboard after sendkeys or sendvalue

## Details
currently after using sendkeys, I have manually hide the keyboard. Doing this for every textbox is cumbersome.

```
$.sendKeys();
if(((AndroidDriver )(WebDriverRunner.getDriver)).isKeyboardShown()){
 // hideKeyboard call
} else if ios{
//getIosDriver and hide keyboard
}
```

I think of 2 ways to implement this.

1. add command called hideKeyboard 

$.setValue().hideKeyboard();
$.sendKeys(); $.hidekeyboard(); //since sendkeys is void we cannot chain it

2. Implicitly add hideKeyboard inside the setvalue method. (Very simple to implement but cannot be used after sendkeys

```
private void hideKeyboardIfPresent() {
    if (isAndroidDriver() && AppiumDriverRunner.getAndroidDriver()
      .isKeyboardShown()) {
      AppiumDriverRunner.getAndroidDriver()
        .hideKeyboard();
    } else if (isIosDriver() && AppiumDriverRunner.getAndroidDriver()
      .isKeyboardShown()) {
      AppiumDriverRunner.getIosDriver()
        .hideKeyboard();
    }
  }
```

## Tell us about your environment
* **Selenide Version**:  6.10.0
* **Selenide-Appium Version**:  2.3.0
* **IOS\Android\WEB version**:  NA

## Code To Reproduce Issue [ Good To Have ]
Not applicable

**Comment by amuthansakthivel** [comment]
@BorisOsipov - Could you please suggest which approach we can follow? I can create. a PR for this.

**Comment by amuthansakthivel** [comment]
@asolntsev - Any hint on this one. I can create a PR if I get some hints

**Comment by asolntsev** [comment]
@amuthansakthivel Isn't it already solved by https://github.com/selenide/selenide-appium/pull/131 ?

**Comment by asolntsev** [comment]
Yes, ideally, we should make it chainable.
But at the moment, it seems requires too big refactoring in Selenide. 

Another option - probably much better! - is the following:
1. AppiumSelenideElement should NOT extend SelenideElement. 
2. It will contain only mobile-specific methods. 
Drawback: it makes harder combining web- and mobile tests in the same test class.

**Comment by amuthansakthivel** [comment]
We can park it for a later time then. 

If we can create a method getSelenideAppiumElement in SelenideElement class, then 

$(element).getSelenideAppiumElement().callMobileSpecificMethods()

Drawback you mentioned is an antipattern. People should not combine web and mobile in one tests.

**Comment by asolntsev** [comment]
@amuthansakthivel  Why it's antipattern? Never heard that. 
If I want to test a hybrid mobile app, it seems reasonable to make these steps in a single test:
* open a mobile app, 
* switch to a webview, 
* login in webview,
* and switch back to mobile app. 

> Drawback you mentioned is an antipattern. People should not combine web and mobile in one tests.

**Comment by amuthansakthivel** [comment]
@asolntsev - That makes sense. What about the below option?

If we can create a method getSelenideAppiumElement in SelenideElement class, then

$(element).getSelenideAppiumElement().callMobileSpecificMethods()`

**Comment by asolntsev** [comment]
@amuthansakthivel I don't understand how it's possible. 
Project `selenide-appium` depends on `selenide`, but project `selenide` knows nothing about `selenide-appium`. 
That's why class `SelenideElement` cannot have method returning `SelenideAppiumElement`. 

But what is possible - to override ALL methods of `SelenideElement` (applicable for mobile apps) in `SelenideAppiumElement`. So that all these methods would return `SelenideAppiumElement` instead of `SelenideElement`.

**Comment by amuthansakthivel** [comment]
@asolntsev - yes you are correct. My bad. I think we should then override applicable methods

**Comment by amuthansakthivel** [comment]
Please close this issue @asolntsev
