### ISSUE TITLE
Wrapper method in Selenide Appium to switchToSpecificContext

### ISSUE THREAD

**Issue by amuthansakthivel** [selenide/selenide-appium#102]
## The problem - Feature Request

Currently, there is no wrapper methods to switch to different context. (native to web view or web to native view)

We can add two methods getContextHandles and setContext(String contextName) in SelenideAppium

```
public static Set<String> getContextHandles(){
    return AppiumDriverRunner.isAndroidDriver() 
      ? AppiumDriverRunner.getAndroidDriver().getContextHandles()
      : AppiumDriverRunner.getIosDriver().getContextHandles()
  }
```
```
public static void setContext(String contextName){
   if( AppiumDriverRunner.isAndroidDriver()){
     AppiumDriverRunner.getAndroidDriver().context(contextName);
} else if(AppiumDriverRunner.isIosDriver()){
    AppiumDriverRunner.getIosDriver().context(contextName);
} else{
 //throw runtime exception
}

```
## Details
Currently users have to find whether it is android or ios and get the instance of android or ios driver and then switch to context

**Comment by BorisOsipov** [comment]
Should be implemented like com.codeborne.selenide.Selenide#switchTo`

**Comment by asolntsev** [comment]
@amuthansakthivel In this case, we don't need to check if driver is Android or iOS. They both implement interface `org.openqa.selenium.ContextAware` that has methods `context` and `getContextHandles`.
