### ISSUE TITLE
Adding method to scroll to end\start of screen in appium

### ISSUE THREAD

**Issue by amuthansakthivel** [selenide/selenide-appium#104]
## The problem : Feature request

Sometimes we may want to scroll to the end of the screen to perform some actions. 

## Details
It will be good if we have a method in SelenideAppium for it. 

We can reuse the implementation from https://github.com/selenide/selenide-appium/pull/89 without the element is displayed condition.

**Comment by BorisOsipov** [comment]
@amuthansakthivel scroll for the start of screen in scope of this feature too.

**Comment by amuthansakthivel** [comment]
@BorisOsipov - Makes sense. Should we put this in SelenideAppium class as it is irrelevant to SelenideElement

**Comment by asolntsev** [comment]
@amuthansakthivel Isn't it solved by https://github.com/selenide/selenide-appium/pull/139?

**Comment by amuthansakthivel** [comment]
That PR, scrolls to find the element. But sometimes we just wanted to scroll to the end or top. I cannot think of an appealing reason to have this. I can create a PR to solve this issue if you think it is needed.

SelenideAppium.scrollToBottomOfScreen();
SelenideAppium.scrollToTopOfScreen();

**Comment by asolntsev** [comment]
@amuthansakthivel I am not sure it's really needed. At least I never needed it in my projects.
