### ISSUE TITLE
Adding overloaded $ and $$ method that accepts By for Android and IosLocators

### ISSUE THREAD

**Issue by amuthansakthivel** [selenide/selenide-appium#106]
## Feature Request

Currently if there is a need for dynamic XPath or there is a need to use By locator for android and ios app, then we have to create a wrapper method called `click(By androidBy, By iosBy)`

```java
public static void click(By androidBy, By iosBy){
  $(getByBasedOnDriver()).shouldBe(visible).click();
}

private static By getByBasedOnDriver(){
  return androidBy if android and iosBy otherwise
}

public static void click(By androidBy, By iosBy, Condition condition, Duration duration){
  $(getByBasedOnDriver()).shouldBe(condition, duration).click();
}
```

The case gets even tougher when we have to also pass the Condition like visible, enabled and time to wait

## Details
If we have a `$` , `element`, `$$`, `elements` method overloaded - we can accept androidBy, iosBy and can automatically use the appropriate by based on the check instance of `AndroidDriver`. It will make life so easy for testers.

PS: What if we create `SelenideAppiumElement` class instead of reusing `SelenideElement`? @asolntsev @BorisOsipov

**Comment by BorisOsipov** [comment]
We choose an approach how we will handle such cases when we have to use different selectors\conditions for the same SelenideElement with different app driver under hood. Will we have build-in support or not?

The same question for https://github.com/selenide/selenide-appium/issues/10

**Comment by asolntsev** [comment]
@BorisOsipov @amuthansakthivel I added method `$`: https://github.com/selenide/selenide-appium/pull/131

Initially, this PR doesn't solve the problem with two selectors (Android and iOS selectors). It just extends classical `SelenideElement` with additional methods.
