### ISSUE TITLE
Handling stale element exception in $$ and elements method

### ISSUE THREAD

**Issue by amuthansakthivel** [selenide/selenide-appium#107]
## The problem
When using $$ and elements method, I get stale element reference exception while operating. So either I have to wait for one element or use static waits before operating.

let's say I perform a screen navigation from ScreenA to ScreenB and both screens have static elements

```java
class ScreenA {
  methodA() {
    clickOnA();
    return new ScreenB()
  }
}

 class ScreenB {
  @AndroidFindBy(xpath = "//android.widget.TextView")
  @iOSXCUITFindBy(xpath = "//XCUIElementTypeStaticText")
  private List<WebElement> staticTexts;

  public void checkStaticTexts() {
    $$(staticTexts).shouldBe(sizeGreaterThan(1)).shouldHave(exactText("abcd","abcd123"));
  }
}
```

Appium Logs - https://gist.github.com/amuthansakthivel/89eb43eaf0affe1f54b793646194c939

## Tell us about your environment
* **Selenide Version**:  6.10.0
* **Selenide-Appium Version**: 2.3.1
* **IOS\Android\WEB version**:  NA

## Code To Reproduce Issue [ Good To Have ]
Please remember that with sample code it's easier to reproduce the bug.

**Comment by BorisOsipov** [comment]
@amuthansakthivel $$ handles Stale Element exception. Could you share selenide stacktrace?

**Comment by amuthansakthivel** [comment]
@BorisOsipov - Please find the logs https://gist.github.com/amuthansakthivel/8b1375ae2c858ae7598248c1b8a2efe7

**Comment by asolntsev** [comment]
@amuthansakthivel From your code, we don't see how you initialize instance of `ScreenB`. You wrote `return new ScreenB()`, but it cannot be true: then `staticTexts` would be null. 

P.S. I guess the problem is that you declare `List<WebElement>`. Declare it as `ElementsCollection`:

```java
class ScreenB {
  @AndroidFindBy(xpath = "//android.widget.TextView")
  @iOSXCUITFindBy(xpath = "//XCUIElementTypeStaticText")
  private ElementsCollection staticTexts;

  public void checkStaticTexts() {
    staticTexts.shouldBe(sizeGreaterThan(1)).shouldHave(exactText("abcd","abcd123"));
  }
}
```

**Comment by amuthansakthivel** [comment]
@asolntsev - Yes, I will try with ElementCollection then

**Comment by amuthansakthivel** [comment]
Working fine after using ElementsCollection. Will reopen the issue if faced again.
