### ISSUE TITLE
High priority bug - cannot access org.openqa.selenium.Rotatable [ERROR] 

### ISSUE THREAD

**Issue by amuthansakthivel** [selenide/selenide-appium#108]
## The problem
I have been using selenide-appium version 2.3.0 and suddenly I get a compilation error when try to cast WebDriverRunner.getDriver to AndroidDriver or IosDriver

## Details
Recently I started to get a compilation error in an existing project which worked so far well

((IOSDriver) DriverManager.getDriver()).hideKeyboard(); 
((AndroidDriver) DriverManager.getDriver())
        .pressKey(new KeyEvent(AndroidKey.valueOf("DIGIT_" + c)));

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project CBH-Automation-Framework: Compilation failure
[ERROR] /xx/xxx/AppiumUtils.java:[198,44] cannot access org.openqa.selenium.Rotatable
[ERROR]   class file for org.openqa.selenium.Rotatable not found

## Tell us about your environment
* **Selenide Version**: 6.10
* **Selenide-Appium Version**: 2.3.0 and 2.3.1
* **IOS\Android\WEB version**: NA

## Code To Reproduce Issue [ Good To Have ]
Please remember that with sample code it's easier to reproduce the bug.

**Comment by amuthansakthivel** [comment]
@BorisOsipov @asolntsev

**Comment by asolntsev** [comment]
@amuthansakthivel I cannot reproduce the problem.
Just tried with latest Appium (8.3.0) and Selenide (6.10.2-SNAPSHOT) - worked for me.

**Comment by amuthansakthivel** [comment]
@asolntsev - I was using the selenide-appium dependency before. Should I manually include the selenide version?

Could we please also include the appium and selenium version in the changelog of our selenide-appium repo. It can help us to backtrack the transitive dependencies.

**Comment by asolntsev** [comment]
@amuthansakthivel No, you don't need to include any versions manually.
Just try to upgrade to `selenide-appium:2.4.0-SNAPSHOT`. Does it help?

P.S. Yes I always include Selenide, Selenium and Appium version upgrades in https://github.com/selenide/selenide-appium/blob/main/CHANGELOG.

**Comment by amuthansakthivel** [comment]
Thank you so much @asolntsev

**Comment by amuthansakthivel** [comment]
@asolntsev - Could you please publish a snapshot version 2.4.0

**Comment by asolntsev** [comment]
@amuthansakthivel I think I already published `2.4.0-SNAPSHOT`.
But just in case, i have published it once again right now.

I think you cannot see SNAPSHOTS in Nexus. 
The proper URL of snapshot dependencies is like this:

https://oss.sonatype.org/content/repositories/snapshots/com/codeborne/selenide-appium/2.4.0-SNAPSHOT/selenide-appium-2.4.0-20221207.150138-1.pom

**Comment by amuthansakthivel** [comment]
I can see it now even in nexus. Thank you so much @asolntsev

**Comment by amuthansakthivel** [comment]
It is working fine. Closing this issue
