### ISSUE TITLE
Collective usage of Selenide-Appium adapter and Selenide dependency in one project

### ISSUE THREAD

**Issue by IlyaUk** [selenide/selenide-appium#111]
Hi @asolntsev,
Could you please advice whether or not it is possible to use 'Selenide-Appium' and 'Selenide for web' dependencies in one project together?

In my case we have the following:
**Given:** 
- multi-module Gradle project

  - core module
  has dependency Selenide

      - module with ui tests
      uses selenide from core
 
      - module with ui + mobile tests
      uses selenide from core + has Selenide-Appium dependency 

**Issue:** An attempt to run a web test in a child module (where Selenide-Appium is available) results in our particular case in the following error when we try to click a button on web using JavaScript ($(locator).click(usingJavaScript()): 

```
java.lang.ClassCastException: class com.codeborne.selenide.ClickOptions cannot be cast to class com.codeborne.selenide.appium.AppiumClickOptions (com.codeborne.selenide.ClickOptions and com.codeborne.selenide.appium.AppiumClickOptions are in unnamed module of loader 'app')

	at com.codeborne.selenide.appium.commands.AppiumClick.execute(AppiumClick.java:39)
	at com.codeborne.selenide.appium.commands.AppiumClick.execute(AppiumClick.java:28)
	at com.codeborne.selenide.commands.Commands.execute(Commands.java:158)
	at com.codeborne.selenide.impl.SelenideElementProxy.dispatchAndRetry(SelenideElementProxy.java:130)
	at com.codeborne.selenide.impl.SelenideElementProxy.invoke(SelenideElementProxy.java:82)
	at jdk.proxy2/jdk.proxy2.$Proxy44.click(Unknown Source)
```

As we can see when we reach during test runtime a method 'getCommand' in com.codeborne.selenide.commands.Commands class, variable _private final Map<String, Command<?>> commands = new ConcurrentHashMap<>(128)_ has commands not from 'Selenide for web' but from 'Selenide-Appium' dependency ('Click()' is replaced by 'AppiumClick()' for example).

```
Environment:
JDK 8
Gradle 7.4.1
Selenide 6.10.1
Selenide-Appium 2.4.0
```

**Comment by asolntsev** [comment]
@IlyaUk Yes, the idea is that you can use `selenide-appium` for testing both mobile and web in the same project. You don't even need to split your project to submodules.

In this case, `ClassCastException` is a fresh bug in `selenide-appium`. Will fix it asap. Thank you for reporting.

**Comment by IlyaUk** [comment]
Thanks a lot for the reply and clarifications.
