### ISSUE TITLE
Upgrading to Selenide 5.2.2 causes Compilation Error

### ISSUE THREAD

**Issue by ProNationWolf** [selenide/selenide-appium#15]
ScreenObject.java :

    /**
     * Initialize a Page Object fields annotated with @FindBy, @AndroidFindBy, @iOSFindBy etc.
     */
    public static <PageObjectClass, T extends PageObjectClass> PageObjectClass screen(T pageObject) {
        SelenidePageFactory.initElements(new SelenideAppiumFieldDecorator(getWebDriver()), pageObject);
        return pageObject;
    }

Error : Description	Resource	Path	Location	Type
The import com.codeborne.selenide.SelenidePageFactory cannot be resolved	

SelenideAppiumFieldDecorator:

    @Override
    public Object decorate(ClassLoader loader, Field field) {
        builder.setAnnotated(field);
        By selector = builder.buildBy();

        if (selector == null) {
            selector = new Annotations(field).buildBy();
        }

        if (selector instanceof ByIdOrName) {
            return decorateWithAppium(loader, field);
        } else if (SelenideElement.class.isAssignableFrom(field.getType())) {
            return ElementFinder.wrap(searchContext, selector, 0);
        } else if (ElementsCollection.class.isAssignableFrom(field.getType())) {
            return new ElementsCollection(new BySelectorCollection(searchContext, selector));
        } else if (ElementsContainer.class.isAssignableFrom(field.getType())) {
            return createElementsContainer(selector, field);
        } else if (isDecoratableList(field, ElementsContainer.class)) {
            return createElementsContainerList(field);
        } else if (isDecoratableList(field, SelenideElement.class)) {
            return SelenideElementListProxy.wrap(factory.createLocator(field));
        }

Errors :  
The method wrap(Driver, String, int) in the type ElementFinder is not applicable for the arguments (SearchContext, By, int)
The method wrap(Driver, String, int) in the type ElementFinder is not applicable for the arguments (SearchContext, By, int)
The constructor SelenideFieldDecorator(SelenideElement) is undefined

Suggestion : 

Can we merge this code with the mainline Selenide Project , so that these issues are not encountered whenever a new version is released.

**Comment by asolntsev** [comment]
Yes, I will merge with Selenide master branch asap.

**Comment by ProNationWolf** [comment]
Hi @asolntsev  , any updates ?

**Comment by asolntsev** [comment]
@ProNationWolf Sorry for the delay. We recently released selenide-appium 1.3 (+selenide 5.2.6 recommended). They should work well together.
