### ISSUE TITLE
Slow performance in scroll actions - iOS

### ISSUE THREAD

**Issue by umesh-Ideahub** [selenide/selenide-appium#153]
## The problem
I'm currently using appium-selenide with cucumber, and I'm using scroll feature which introduced recently, but it performs really slowly, and it always waits few seconds before start scrolling. Even after scrolling, if there's any action to perform like click, then it waits another few seconds to perform that action. Scroll action performed in android is working as expected, but I'm facing this issue only on iOS.

**Environment**
Selenide-Appium Version - 2.7.1
Appium Version - 2.0
iOS- 16.1 (emulator)

## Code To Reproduce Issue
Tried both options mentioned below
```java
$(element).scrollTo().click(tap());
$(element).scroll(with(DOWN, 2)).click(tap());
```

**Comment by asolntsev** [comment]
@umesh-Ideahub Thank you for reporting. I also would like to make scrolling faster. But how?

**Comment by asolntsev** [comment]
@amuthan-sakthivel @amuthansakthivel  Do you have any ideas how to make scrolling faster?

**Comment by amuthansakthivel** [comment]
@asolntsev - It seems there is some change in the recent version of appium or may be with selenide. I will work on this over the weekend and sort this out

**Comment by amuthansakthivel** [comment]
@umesh-Ideahub - could you please provide the appium server log and more details about where you are running your tests. 

Browserstack or local machine

**Comment by umesh-Ideahub** [comment]
@amuthansakthivel Sorry for the late reply. I'm running my scripts locally with simulators provided with Xcode. Will provide you appium server logs.

**Comment by amuthansakthivel** [comment]
@asolntsev - driver.getPageSource is taking around 6 to  9 seconds to return the response which is causing the delay. I cannot confirm if this is caused because of latest appium client or the appium server or the xcuitest driver.  I will find a optimised way to solve this problem
