### ISSUE TITLE
Unable to find find list of elements by some strategy

### ISSUE THREAD

**Issue by rosolko** [selenide/selenide-appium#4]
The problem - trying to find list of elements using annotations with strategy:
```java
@AndroidFindBy(id = "country_code")
private ElementsCollection countryCodes;
```
And getting an error:
```java
java.lang.NullPointerException
```

But it works fine if using direct search:
```java
$$(By.id("country_code")).<some_action>
```

**Comment by asolntsev** [comment]
@rosolko Yes, we need to implement support for `@AndroidFindBy` and `@...IPhone..FindBy` annotations. Feel free to prepare a pull request :)

**Comment by asolntsev** [comment]
it was fixed a long time ago.
