### ISSUE TITLE
clipboard().getText() returns changed copied content 

### ISSUE THREAD

**Issue by ivershin** [selenide/selenide-appium#56]
The app that I'm testing has a functionality of copying URLs to the clipboard, I've used `clipboard().getText()` to test that the copied URL is correct but it looks like when I'm using this method something else is added to the initial string, something like an invisible first symbol which breaks the URL, weird right? Because when I drop the first symbol everything works fine.

I've also tried using Appium's `driver.getClipboardText() ` and had no such issues there.

**Comment by asolntsev** [comment]
@ivershin I just released `selenide-appium:1.6.10`, it should use `AppiumDriver.getClipboardText()` instead of Selenide default implementation. Please check if it helps.

**Comment by ivershin** [comment]
@asolntsev looks like it works, thanks 🙏

**Comment by asolntsev** [comment]
@ivershin juhuu!
Thank you for reporting the issue with a solution idea.
