### ISSUE TITLE
add  possibility  switching  to web  config  for  mix  web and mobile tests 

### ISSUE THREAD

**Issue by onikitchukGain** [selenide/selenide-appium#60]
after 

 === 1.6.2 (released 24.02.2021)
* #52 override Selenide standard method $.dragAndDropTo()
* upgrade to Selenide 5.19.0

 we override dragAndDropTo()  for web too, 
SelenideAppiumCommands.class and  other.

need to add possibility switch config to the web during execution E2E test which involves web and mobile.

**Comment by asolntsev** [comment]
@onikitchukGain method `$.click()` and `$.dragAndDrop()` now detect if the webdriver is mobile or web.
Fixed in `selenide-appium 1.7.3`, will appear in Maven central repo in a few minutes.

**Comment by onikitchukGain** [comment]
@asolntsev  thanks for fast  improvment
