### ISSUE TITLE
Upgrade to Appium 8 (Selenium 4)

### ISSUE THREAD

**Issue by asolntsev** [selenide/selenide-appium#65]
See https://github.com/appium/java-client/blob/master/docs/v7-to-v8-migration-guide.md

**Comment by asolntsev** [comment]
wow. Thumbs up!

**Comment by rosolko** [comment]
@sobolewska Thanks! Stick to migration notes - let's get rid of `DesiredCapabilities` at least for `AndroidDriverProvider.java` and `AndroidDriverWithDemos.java`. Also right after setting up caps you need to merge them with an original once that receivein by overrided method by `capabilities.merge(desiredCapabilities)`

**Comment by sobolewska** [comment]
Further work done. Got rid of DesiredCapabilities. 
Tested with iOS. 
If I'll find some time over weekend I'm gonna setup Android env to test vs Android. 
If you lads have the env already in place, maybe you can run the tests and make sure it also works with Android?

**Comment by asolntsev** [comment]
@sobolewska Wow, thank you for the effor!
Sure, I can test the change on Android. Will do it soon.

**Comment by asolntsev** [comment]
@sobolewska I have tested your branch [65Appium8](https://github.com/sobolewska/selenide-appium/tree/65Appium8) on Android emulator - it works. **Feel free to submit a pull request!**

**Comment by asolntsev** [comment]
released `selenide-appium:2.0.0`
