### ISSUE TITLE
Wrappers over AndroidDriver commands in Selenide-Appium

### ISSUE THREAD

**Issue by IlyaUk** [selenide/selenide-appium#78]
Hi @asolntsev,
May I ask you please to help me with clarification of the following question:
Does Selenide-Appium have methods/wrappers to work with Android native keyboard? The one that can be accessed through AndroidDriver instance like:
`(WebDriverRunner.getWebDriver() as AndroidDriver).pressKey(KeyEvent(DIGIT_0))`
If not maybe there are some plans in the nearest future to implement such wrappers in Selenide-Appium?
Thanks a lot in advance for the help.

**Comment by asolntsev** [comment]
@IlyaUk 
1. Yes, you can use this code to access native keyboard: `(WebDriverRunner.getWebDriver() as AndroidDriver).pressKey(KeyEvent(DIGIT_0))`
2. Yes, we can implement some more concise syntax for accessing `AndroidDriver` and its methods. Do you have concrete ideas how this syntax could look like?

**Comment by admizh** [comment]
Also you can use this:
```java
Optional<AppiumDriver> appiumDriver = com.codeborne.selenide.appium.WebdriverUnwrapper.cast(webDriver, AppiumDriver.class);
or
Optional<AndroidDriver> appiumDriver = WebdriverUnwrapper.cast(webDriver, AndroidDriver.class);

```

**Comment by amuthansakthivel** [comment]
Hi @asolntsev 

What about WebDriverRunner.getAppiumDriver() or WebDriverRunner.getAndroidDriver()

**Comment by amuthansakthivel** [comment]
@asolntsev @BorisOsipov  - This issue is covered in https://github.com/selenide/selenide-appium/pull/100
