### ISSUE TITLE
Cannot find element using method 'sibling'

### ISSUE THREAD

**Issue by jstefek** [selenide/selenide-appium#79]
Observed the problem, when using AndroidDriver/UiAutomator2.

Example:
When I update current test AndroidDragAndDropTest#dragAndDrop on the first line.
Replacing: 
```
$(By.xpath(".//*[@text='Views']")).click();
```
By:
```
$(By.xpath(".//*[@text='Text']")).sibling(0).click();
```
I get:
```
Element not found {By.xpath: .//*[@text='Text']/By.xpath: following-sibling::*[1]}
Expected: exist
Screenshot: *
Page source: *
Timeout: 4 s.
Caused by: NoSuchElementException: An element could not be located on the page using the given search parameters.
Element not found {By.xpath: .//*[@text='Text']/By.xpath: following-sibling::*[1]}
Expected: exist
Screenshot: *
Page source: *
Timeout: 4 s.
Caused by: NoSuchElementException: An element could not be located on the page using the given search parameters.
	at app//com.codeborne.selenide.impl.WebElementSource.createElementNotFoundError(WebElementSource.java:87)
	at app//com.codeborne.selenide.impl.ElementFinder.createElementNotFoundError(ElementFinder.java:138)
	at app//com.codeborne.selenide.impl.ExceptionWrapper.wrap(ExceptionWrapper.java:32)
	at app//com.codeborne.selenide.impl.SelenideElementProxy.dispatchAndRetry(SelenideElementProxy.java:151)
	at app//com.codeborne.selenide.impl.SelenideElementProxy.invoke(SelenideElementProxy.java:81)
	at app/jdk.proxy3/jdk.proxy3.$Proxy17.click(Unknown Source)
	at app//com.codeborne.selenide.appium.demos.AndroidDragAndDropTest.dragAndDrop(AndroidDragAndDropTest.java:20)
...
```

But following works: 
```
$(By.xpath(".//*[@text='Text']/following-sibling::*[1]")).click();
```

**Comment by asolntsev** [comment]
@jstefek Yes, it's one of our Selenide puzzlers we presented at Heisenbug conference few years ago. :) 

The trick is that there are multiple elements with text "Text":
```html
<table>
  <tr>
    <td>
      <div id="first">Text</div>
    </td>
  </tr>
  <tr>
    <td>
      <div id="second">Text</div>
      <button>The button</button>
    </td>
  </tr>
</table>
```

The first one hasn't sibling, while the second one has sibling.

1. Code `$(By.xpath(".//*[@text='Text']"))` find **the first element** with text "Text". And `.sibling(0)` finds **its** sibling (which doesn't exist).
2. Code `$(By.xpath(".//*[@text='Text']/following-sibling::*[1]"))` finds **some element** that has a sibling. In my example - it's **the second** "Text".

**Comment by jstefek** [comment]
Oh yes, I know such limitation, have faced it many times.

But imho this is not the case.

Proof:
When I opened the app in Appium Inspector, and tried to find the element by xpath with `.//*[@text='Text']`, it found only one element, so there are no more such elements.
To check the inspector does not always return one element, I checked xpath `.//*[@text]`, which found many elements.

So could you please give it one more try?
Btw in Chrome the 'sibling' worked as expected. Just with selenide-appium.

**Comment by asolntsev** [comment]
@jstefek Thanks, now I understand the problem. 
It seems to be a bug (or disability?) of Appium. It doesn't find the element using `following-sibling`. 

Look, this is pure Selenium/Appium code without any Selenide:
1. `webdriver.findElement(By.xpath("//*[@resource-id='com.android.calculator2:id/digit_2']/following-sibling::*[1]"));`  -> finds the eleement
2. `webdriver.findElement(By.xpath("//*[@resource-id='com.android.calculator2:id/digit_2']")).findElement(By.xpath("following-sibling::*[1]"))`  -> `NoSuchElementException`

**Comment by jstefek** [comment]
could be this one? https://github.com/appium/appium/issues/12806
seems like it works as designed, unfortunately

**Comment by asolntsev** [comment]
@jstefek yes, I think it's that issue.
Then it's even strange that such XPath works in Selenium. :)
