### ISSUE TITLE
AppiumElementDescriber trying to get all the attributes of an element for logging and it takes so much of time

### ISSUE THREAD

**Issue by amuthansakthivel** [selenide/selenide-appium#88]
## The problem
AppiumElementDescriber trying to get all the attribute for a missing element resulting in selenide-appium trying to operate on a element more than the desired period.

For logging the successful or failure of event, selenide tries to collect the element information like tag name , text. During remote run it takes considerable amount of time.

Atleast we need to have the capability to disable this plugin. 
It should otherwise lazily evaluate the logging information
Instead of 10 sec spent on a element 2 mins is spent

## Details

This is just an example.
selenide appium version : 2.3.0 
Run environment : Appium version 1.21, Browserstack cloud

if element is present i want to click else I want to ignore (I knew this is not a good idea but just for example)

let's assume the wait time is 10 sec

```
try{
$(element).shouldBe(visible, ofSeconds(waitTime)).click()
}
catch(Exception e){
//Dont do anything
}

$(element2).shouldBe(visible).click();
```
Even after 10s, the appium describer is trying to fetch the attributes to log. It takes almost 2 mins to poll and move to next statement to operate on element2.

[INFO] 2022-11-25 13:39:48,174 [AppiumElementDescriber]: Failed to get attribute class: org.openqa.selenium.NoSuchElementException: Can't locate an element by this strategy: By.chained({By.xpath: //android.widget.Button[@text='Not Now']})
..........
..........
[INFO] 2022-11-25 13:41:44,538 [AppiumElementDescriber]: Failed to get attribute value: org.openqa.selenium.NoSuchElementException: Can't locate an element by this strategy: By.chained({By.xpath: //android.widget.Button[@text='Not Now']})

## Tell us about your environment
* **Selenide Version**: 6.10
* **Selenide-Appium Version**: 2.3.0
* **IOS\Android\WEB version**: both android and ios

## Code To Reproduce Issue [ Good To Have ]
Please remember that with sample code it's easier to reproduce the bug.

**Comment by asolntsev** [comment]
@amuthansakthivel I cannot reproduce the problem.

Does this problem happen during Android or iOS tests? 
1. I see xpath `//android.widget.Button` which probably means it's Android. 
2. But I see that class `AppiumElementDescriber` doesn't even try to log `value` attribute in case of Android:
```java
  protected List<String> androidAttributes() {
    return asList(
      "resource-id", "checked", "content-desc",
      "enabled", "focused", "package",
      "name", "className", "bounds", "displayed"
    );
  }
```

**Comment by BorisOsipov** [comment]
@amuthansakthivel 

3) can you check that you don't set implicit wait timeout? Appium server logs will be helpfull.

**Comment by amuthansakthivel** [comment]
@asolntsev @BorisOsipov 
1. It happens for both android and ios. 
2. Attached the appium logs and appium described logs for your reference
3. No, I have not used any implicit wait

AppiumElementDescriber is trying to log attribute information of element that is not at all available which is causing the issue. 

@asolntsev I think this should be code which is trying to get resource-id which is not present in ios
```

 @Nonnull
  @Override
  public String briefly(Driver driver, @Nonnull WebElement element) {
    return new Builder(element, driver.getWebDriver(), supportedAttributes(driver))
      .appendTagName()
      .appendAttribute("resource-id")
      .finish()
      .build();
  }
```

**Comment by BorisOsipov** [comment]
@amuthansakthivel thanks for the error stacktrace it significantly helps to find one of possible culprit.

```
Caused by: org.openqa.selenium.TimeoutException: Expected condition failed: waiting for io.appium.java_client.pagefactory.AppiumElementLocator$WaitingFunction@696e9e14 (tried for 1 second(s) with 500 milliseconds interval)
	at org.openqa.selenium.support.ui.FluentWait.timeoutException(FluentWait.java:263)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:231)
	at io.appium.java_client.pagefactory.AppiumElementLocator.waitFor(AppiumElementLocator.java:99)
	at io.appium.java_client.pagefactory.AppiumElementLocator.findElement(AppiumElementLocator.java:119)
	... 40 more
```
`FluentWait.timeoutException` looks suspicious. 

This is a built-in wait from appium pagefactory:
```
FluentWait<Supplier<T>> wait = new FluentWait<>(supplier)
	.ignoring(NoSuchElementException.class);
wait.withTimeout(duration);
``` 
Default timeout comes from https://github.com/appium/java-client/blob/master/src/main/java/io/appium/java_client/pagefactory/AppiumFieldDecorator.java#L64

I change timeout to zero in https://github.com/selenide/selenide-appium/pull/92

**Comment by BorisOsipov** [comment]
@amuthansakthivel could you share [appium logs from browserstack](https://www.browserstack.com/docs/app-automate/appium/debug-failed-tests/appium-logs)? it will be helpful to investigate what is it exactly caused the performance issue.

**Comment by amuthansakthivel** [comment]
@BorisOsipov - I have attached in the same gist. Please scroll down to see other files I have added.

https://gist.github.com/amuthansakthivel/c3d3997b33468832fdfcec2dd401d881#file-android-appium-logs-txt
https://gist.github.com/amuthansakthivel/c3d3997b33468832fdfcec2dd401d881#file-ios-appium-describer-logs-txt
https://gist.github.com/amuthansakthivel/c3d3997b33468832fdfcec2dd401d881#file-ios-appium-log-txt

**Comment by BorisOsipov** [comment]
@amuthansakthivel Thanks. My bad. I haven't scroll.

I don't found smth suspicious in the logs. A bit changed AppiumElementDescriber in https://github.com/selenide/selenide-appium/pull/95

**Comment by BorisOsipov** [comment]
@amuthansakthivel could you please test with `selenide-appium:2.3.1`?

**Comment by amuthansakthivel** [comment]
@BorisOsipov - Yes, the issue is fixed with the latest version in **android**. 

**_But in ios, it is still trying to look for an attribute called resource-id which is not present._**

The appium server logs I attached before still holds true. 

This code seems to be the culprit

```
@Nonnull
 @Override
 public String briefly(Driver driver, @Nonnull WebElement element) {
    return new Builder(element, driver.getWebDriver(), supportedAttributes(driver))
      .appendTagName()
      .appendAttribute("resource-id")
      .finish()
      .build();
  }
```

It keeps repeating the below statement : 

[INFO] 2022-11-29 09:58:05,713 [AppiumElementDescriber]: Failed to get attribute resource-id: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: The attribute 'resource-id' is unknown. Valid attribute names are: (
    UID,
    accessibilityContainer,
    accessible,
    enabled,
    frame,
    index,
    label,
    name,
    rect,
    selected,
    type,
    value,
    visible,
    wdAccessibilityContainer,
    wdAccessible,
    wdEnabled,
    wdFrame,
    wdIndex,
    wdLabel,
    wdName,
    wdRect,
    wdSelected,
    wdType,
    wdUID,
    wdValue,
    wdVisible
)

@asolntsev

**Comment by asolntsev** [comment]
Should be solved by https://github.com/selenide/selenide-appium/pull/97
